config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'users/registrations' }
    authenticated :user do

      root 'users#home', as: :authenticated_root
      get '/home', to: 'users#home'
    end

    root 'landings#index'

    resources :users, only: [:index, :show, :edit, :update]
    resources :landings, only: [:index]

    resources :personal_messages, only: [:new, :create]
    resources :conversations, only: [:index, :show]


    get '/discover', to: 'events#discover'
    get '/gymbuddy', to: 'users#gym_buddy'

    resources :events do
      resources :tickets, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

end

app/models/conversation.rb
class Conversation < ApplicationRecord

  belongs_to :author, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  has_many :personal_messages, -> { order(created_at: :asc) }, dependent: :destroy

  validates :author, uniqueness: {scope: :receiver}

  scope :participating, -> (user) do
    where("(conversations.author_id = ? OR conversations.receiver_id = ?)", user.id, user.id)
  end
#  with is a method that returns the other participant of a conversation
  def with(current_user)
    author == current_user ? receiver : author
  end

  scope :between, -> (sender_id, receiver_id) do
    where(author_id: sender_id, receiver_id: receiver_id).or(where(author_id: receiver_id, receiver_id: sender_id)).limit(1)
  end
# ...

  def participates?(user)
    author == user || receiver == user
  end

end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  before_action :set_conversation, except: [:index]
  before_action :check_participating!, except: [:index]

  def index
    @conversations = Conversation.participating(current_user).order('updated_at DESC')
    respond_to do |format|
      format.html
      format.js
    end
    
  end

  def show
    @conversation = Conversation.find_by(id: params[:id])
    @personal_message = PersonalMessage.new
  end

  private

  def set_conversation
    @conversation = Conversation.find_by(id: params[:id])
  end

  def check_participating!
    redirect_to root_path unless @conversation && @conversation.participates?(current_user)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/views/conversations/_conversation.html.erb
<%= link_to conversation_path(conversation) do %>
  <div class=conversation>
      <h3 class="convoHeading">Conversation with</h3>
    <div class="convoUserFlexContainer">
      <%= online_status conversation.with(current_user) %>
      <div class="userChatAvatar">
        <% if conversation.with(current_user).avatar.attached? %>
        <div class="avatar">
          <%= image_tag url_for(conversation.with(current_user).avatar) %>
        </div>
        <% else %>
        <div class="avatar">
          <%= image_tag(user_avatar(conversation.with(current_user))) %>
        </div>
        <% end %>
      </div>
      <h3 class="convoUser"><%= full_name(conversation.with(current_user)) %></h3>
    </div>
    <p class="convoPreview"><em><%= conversation.personal_messages.last.body.truncate(50) %></em></p>
  </div>
<% end %>

app/views/conversations/index.html.erb
<div class="conversaionPageContainer">
  <div class="navBarContainer">
  <% if current_user %>
    <%= render "shared/nav_bar" %>
  <% else %>
    <%= render "shared/landing_nav_bar" %>
  <% end %>
  </div>

  <section class="convo-box">
    <h1 class="chatsHeading">Chats</h1>
    <% if @conversations.length == 0 %>
      <div class="noUsersFoundCard">
        <h3 class="event-title noMatch">None... yet!</h3>
        <div class="event-icon noMatch"><%= image_tag("friends.svg") %></div>
        <%= link_to gymbuddy_path do %>
          <div class="big-button">Find Gym Buddy</div>
        <% end %>
      </div>
    <% end %>
    <div class="conversations id="conversations">
      <%= render @conversations %>
    </div>
  </section>
</div>

app/views/conversations/index.js.erb
$('#conversations').replaceWith('<%= j render @conversations %>');

app/views/conversations/show.html.erb
<div class="conversaionShowPageContainer">
  <div class="navBarContainer">
    <% if current_user %>
    <%= render "shared/nav_bar" %>
    <% else %>
    <%= render "shared/landing_nav_bar" %>
    <% end %>
  </div>

  <div id="conversation-main">
    <div class="convoHeadingContainer">
      <div class="backButton">
        <%= link_to conversations_path do %>
          <<
        <% end %>
      </div>
      <div class="convoUserFlexContainer">
        <%= link_to user_url(@conversation.with(current_user).id) do %>
        <div class="userChatAvatar">
          <% if @conversation.with(current_user).avatar.attached? %>
          <div class="avatar">
            <%= image_tag url_for(@conversation.with(current_user).avatar) %>
          </div>
          <% else %>
          <div class="avatar">
            <%= image_tag(user_avatar(@conversation.with(current_user))) %>
          </div>
          <% end %>
        </div>
        <h1 class="convoUserHeadingName"><%= full_name(@conversation.with(current_user)) %></h1>
        <% end %>
      </div>
    </div>
    <div id="conversation-body" data-conversation-id="<%= @conversation.id %>">
      <%= render @conversation.personal_messages %>
    </div>
    <div class="submitMessageContainer">
      <p class="convoSendNote">return/enter</p>

      <%= form_for @personal_message do |f| %>
      <%= hidden_field_tag 'conversation_id', @conversation.id %>
      <%= f.text_area :body %>
      <br>

      <% end %>
    </div>
  </div>
</div>