config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'users/registrations' }
    authenticated :user do

      root 'users#home', as: :authenticated_root
      get '/home', to: 'users#home'
    end

    root 'landings#index'

    resources :users, only: [:index, :show, :edit, :update]
    resources :landings, only: [:index]

    resources :personal_messages, only: [:new, :create]
    resources :conversations, only: [:index, :show]


    get '/discover', to: 'events#discover'
    get '/gymbuddy', to: 'users#gym_buddy'

    resources :events do
      resources :tickets, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

end

app/models/user.rb
class User < ApplicationRecord
  has_many :tickets
  has_many :events, through: :tickets
  has_many :owned_events, foreign_key: "user_id", class_name: "Event"

  has_many :comment

  geocoded_by :location
  after_validation :geocode


  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :authored_conversations, class_name: 'Conversation', foreign_key: 'author_id'
  has_many :received_conversations, class_name: 'Conversation', foreign_key: 'received_id'
  has_many :personal_messages, dependent: :destroy
  # active_storage module for giving users avatar photos
  has_one_attached :avatar

  # Define scope for user index 'gym buddy' search
  scope :activity_goal, -> (activity_goal) { where activity_goal: activity_goal }
  scope :fitness_level, -> (fitness_level) { where fitness_level: fitness_level }
  scope :gender, -> (gender) { where gender: gender }



  def name
    email.split('@')[0]
  end

  def online?
    !Redis.new.get("user_#{self.id}_online").nil?
  end

  def full_name
    if first_name && last_name
      "#{first_name} #{last_name}"
    end
  end


end

app/controllers/user_controller.rb
class UserController < ApplicationController
  def index
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new

    @user.email = params[:user][:email]
    @user.password = params[:user][:password]
    @user.password_confirmation = params[:user][:password_confirmation]

    if @user.save?
      redirect_to user_path(@user)

    else
      render :new

    end

  end

  def show
    load_user
    
  end


  private

  def load_user
    @user = User.find(params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController

  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # # GET /resource/sign_up
  # def new
  #   super
  # end
  #
  # # POST /resource
  # def create
  #   super
  # end
  #
  # # GET /resource/edit
  # def edit
  #   super
  # end
  #
  # # PUT /resource
  # def update
  #   super
  # end
  #
  # # DELETE /resource
  # def destroy
  #   super
  # end
  #
  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected
  #
  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end
  #
  # # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end
  #
  # # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end
  #
  # # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end

  # Overwrite the devise path after updating a profile
    def after_update_path_for(resource)
      user_path(resource)
    end

end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def gym_buddy
    # view is used to gather search params for user#index
  end

  def index

    @users = User.all
    # check if location param is passed, then calcualte lon and lat for the location
    if params[:search].present?
      radius = params[:radius];
      search_location_lat = Geocoder.search(params[:search])[0].data["lat"]
      search_location_lon = Geocoder.search(params[:search])[0].data["lon"]
      @users = User.near([search_location_lat, search_location_lon], radius, units: :km)
    end
    @users = @users.where(matching: true)

    filtering_params(params).each do |key, value|
      @users = @users.public_send(key, value) if value.present?
    end


    # Above makes use of filtering_params private method and public_send ruby method to reduce the following redundant code.
    # Also, if more search params are added, they are automatically accounted for.
    # @users = @users.activity_goal(params[:activity_goal]) if params[:activity_goal].present?
    # @users = @users.fitness_level(params[:fitness_level]) if params[:fitness_level].present?
    # @users = @users.gender(params[:gender]) if params[:gender].present?


    if params[:availability_check].present?
      available_users = []
      @users.each do |user|
        current_user.availability.each do |day|
          if user.availability.include?(day)
            available_users << user
            break
          end
        end
      end
      @users = available_users
    end


  end

  def show
    if params[:id]
      @user = User.find(params[:id])
    else
      @user = current_user
    end
      @events = @user.events
      @owned_events = @user.owned_events
  end

  def home
    if current_user
      @user = current_user
      @events = @user.events.where("time > ?", DateTime.now)
      @owned_events = @user.owned_events.order(:time)
    else
      redirect_to "devise/sessions#new"
    end
  end

  def edit
    @user = current_user
  end

  def update
    @user = current_user
    @user.first_name = params[:user][:first_name]
    @user.last_name = params[:user][:last_name]
    @user.age = params[:user][:age]
    @user.gender = params[:user][:gender]
    @user.activity_goal = params[:user][:activity_goal]
    @user.fitness_level = params[:user][:fitness_level]
    @user.location = params[:user][:location]
    @user.description = params[:user][:description]
    @user.matching = params[:user][:matching]

    if params[:user][:availability]
      @user.availability = params[:user][:availability]
    else
      @user.availability = []
    end

    unless params[:user][:avatar] == nil
      @user.avatar.attach(params[:user][:avatar])
    end


    if @user.save
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  private

  # Params that can be used to filter search results
  def filtering_params(params)
    params.slice(:activity_goal, :fitness_level, :gender)
  end


end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/gym_buddy.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>



<section class="create-new-event">
  <div class="gym-buddy-hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Find a Gym Buddy</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll connect you with someone to keep you motivated.</h2>
    </div>
  </div>

  <nav class="search">

    <%= form_tag users_path, method: :get do %>
      <div class="form-card discover">
        <div class="form-item-icon">
          <%= image_tag "worldwide.svg" %>
        </div>
        <div class="form-item">
          <h2 class="activity-type-header">Find People Near</h2>
          <%= text_field_tag :search, current_user.location, id: "locationSearchField" %>
        </div>
        <div class="form-item">
          <h2 class="activity-type-header">Radius</h2>
          <%= select_tag :radius, options_for_select([["1km", 1], ["2km", 2], ["5km", 5], ["10km", 10], ["20km", 20], ["30km", 30], ["40km", 40], ["50km", 50], ["60km", 60], ["70km", 70], ["80km", 80], ["90km", 90], ["100km", 100]], selected: 60), include_blank: false %>
        </div>
      </div>
      <div class="form-card discover">
        <div class="form-item">
          <h2 class="activity-type-header">Who would you prefer to workout with?</h2>
          <%= select_tag :gender, options_for_select([["All", nil], "Female", "Male", "Non-Binary"], selected: "All"), include_blank: false %>
        </div>
      </div>
      <div class="form-card discover">
        <h2 class="activity-type-header">What type of fitness will you be looking to do?</h2>
        <div class="activity-icons-wrapper">
          <div class="activity-icon">
            <p class="activity-type-description">Yoga/Pilates</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Yoga/Pilates", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("lotus-position.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Resistence</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Resistence Training", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("exercise.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Cardio</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Cardio", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("athletics.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Recreation</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Recreation", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("american-football.svg") %>
            </label>
          </div>
          <label class="activity-type hide-radio-button">
            <%= radio_button_tag :activity_type, "", checked = true %>
            <div class="clickedRadioSquare"></div>
            <div class="activity-icon-all">All Types</div>
          </label>
        </div>
      </div>

      <div class="form-card discover">
        <div class="form-item">
          <h2 class="activity-type-header">What fitness level?</h2>
          <%= select_tag :fitness_level, options_for_select([["All", ""], 1, 2, 3], selected: "All"), include_blank: false %>
        </div>
      </div>
        <div class="form-card discover">
          <div class="form-item">
            <label class="fitness-level availabilityCheck">
              <h2 class="activity-type-header-block availabilityCheck">Only show those with matching availability</h2>
              <%= check_box_tag :availability_check, true, checked = false %>
            </label>
          </div>

      </div>
      <div class="form-submit">
        <div class="large-submit-button">
          <%= submit_tag "Find Buddy" %>
        </div>
      </div>
      <% end %>
    </nav>


</section>

app/views/users/home.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>

<div  class="signIn">
<% if !current_user %>
<nav class="sign-in">
  <p>Already a Member?</p>
  <a href="/users/sign_in" class="sign-in-button">Sign In</a>
</nav>
<% end %>
</div>



<section class="home-page">
  <div class="home-hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Your Schedule</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">Look how organized you are.</h2>
    </div>
  </div>
</section>

<section class="event-results home">

  <% if @user == current_user %>
    <% if @events.length > 0 %>
      <div class="event-cards-container">
        <h2 class="home-heading">Upcomming Events</h2>
      <% @events.each do |event| %>
        <%= link_to event_url(event.id) do %>
          <div class="event-card">
            <div class="event-icon-container">
              <div class="event-icon"><%= image_tag(event_activity_icon(event)) %></div>
            </div>
            <div class="event-info">
              <p class="date"><%= event.time.strftime("%A %b %d, %Y") %> • <%= event.time.strftime("%I:%M%p") %></p>
              <h3 class="event-title"><%= event.title %></h3>
              <p class="address"><%= event.address %></p>
            </div>
          </div>
        <% end %>
      <% end %>
      </div>
    <% end %>
    <% if @owned_events.length > 0 %>
      <div class="event-cards-container">
        <h2 class="home-heading">Events You're Hosting</h2>
        <% @owned_events.each do |event| %>
          <%= link_to event_url(event.id) do %>
        <div class="event-card">
          <div class="event-icon-container">
            <div class="event-icon"><%= image_tag(event_activity_icon(event)) %></div>
          </div>
          <div class="event-info">
            <p class="date"><%= event.time.strftime("%A %b %d, %Y") %> • <%= event.time.strftime("%I:%M%p") %></p>
            <h3 class="event-title"><%= event.title %></h3>
            <p class="address"><%= event.address %></p>
          </div>
        </div>
      </div>
          <% end %>
        <% end %>
    <% end %>
    <% if @owned_events.length == 0 && @events.length == 0 %>
      <div class="event-cards-container">
        <p class="no-rsvps">No Upcomming Events...</p>
        <h2 class="home-greeting">Let us help you with that!</h2>
        <%= link_to discover_path do %>
          <div class="big-button">Find Event</div>
        <% end %>
        <div class="greeting-help">
          <%= image_tag("gym.svg") %>
        </div>
      </div>
    <% end %>
  <% end %>
</section>

app/views/users/index.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>


<section class="create-new-event">

  <div class="gym-buddy-hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Find a Gym Buddy</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll connect you with someone to keep you motivated.</h2>
    </div>
  </div>
</section>


<header class="event-index">
  <h1 class="index-header">Refine Your Search</h1>
  <nav class="filter-search">
    <%= form_tag users_path, method: :get do %>

        <%= select_tag :activity_goal, options_for_select([["All Fitness Interests", nil], "Yoga/Pilates", "Resistence Training", "Cardio", "Recreation"], selected: params[:activity_goal]), include_blank: false %>
        <h3 class="label-style-1">Near</h3>
        <%= text_field_tag :search, params[:search], id: "locationSearchField" %>
        <h3 class="label-style-1">Radius</h3>
        <%= select_tag :radius, options_for_select([["1km", 1], ["2km", 2], ["5km", 5], ["10km", 10], ["20km", 20], ["30km", 30], ["40km", 40], ["50km", 50], ["60km", 60], ["70km", 70], ["80km", 80], ["90km", 90], ["100km", 100]], selected: params[:radius]), include_blank: false %>
        <h3 class="label-style-1">Gender</h3>
        <%= select_tag :gender, options_for_select([["All", nil], "Female", "Male", "Non-Binary"], selected: params[:gender]), include_blank: false %>
        <h3 class="label-style-1">Fitness Level</h3>
        <%= select_tag :fitness_level, options_for_select([1, 2, 3, ["All", ""]], selected: params[:fitness_level]), include_blank: false %>

        <%= submit_tag "Filter", id: "filterButton" %>
    <% end %>

  </nav>

</header>


<div class="userResultsBackground">
  <section class="user-results">
    <% if @users.length == 0 %>
    <div class="noUsersFoundCard">
      <h3 class="event-title noMatch">Sorry, No Users Found</h3>
      <div class="event-icon noMatch"><%= image_tag("friends.svg") %></div>
      <p class="address">Please try again</p>
    </div>
    <% else %>
      <% @users.each do |user| %>
        <% unless user == current_user %>
          <%= link_to user_url(user.id) do %>
            <div class="user-card">
              <div class="userIndexAvatar">
                <%= image_tag url_for(user_avatar(user)) %>
              </div>
              <div class="user-card-flex-container">
                <div class="user-card-content">
                  <h3 class="index-user-name"><%= user.full_name %></h3>
                  <p class="fitness-level">Fitness Level: <%= user.fitness_level %></p>
                  <p class="user-location"><%= user.location %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      <% end %>
    <% end %>
  </section>
</div>

app/views/users/show.html.erb
<section class="profileContainer">
  <div class="navBarContainer">
    <% if current_user %>
    <%= render "shared/nav_bar" %>
    <% else %>
    <%= render "shared/landing_nav_bar" %>
    <% end %>
  </div>

  <section class="user-profile-card">
    <div class="flex-profile-card">
      <div class="profileSideFlexContainer">
        <div class="profile-avatar">
          <%= image_tag url_for(user_avatar(@user)) %>
        </div>
        <% if current_user != @user %>
        <div class="messageButtonFlex">
          <button class="messageButton">
            <%= link_to "Message", new_personal_message_path(receiver_id: params[:id]) %>
          </button>
        </div>
        <% end %>
      </div>
      <div class="profile-info">
        <div class="userNameContainer">
          <div class="user-name">
            <div class="profile-avatar-small">
              <%= image_tag url_for(user_avatar(@user)) %>
            </div>
            <h1><%= full_name(@user) %></h1>
          </div>
          <div class="messageButtonSmallContainer">
            <% if current_user != @user %>
              <button class="messageButtonSmall">
                <%= link_to "Message", new_personal_message_path(receiver_id: params[:id]) %>
              </button>
            <% end %>
          </div>
        </div>
        <div class="profileCard">
          <div class="profile-item">
            <h2>Age:</h2> <h3><%= @user.age %></h3>
          </div>
          <div class="profile-item">
            <h2>Gender:</h2> <h3><%= @user.gender %></h3>
          </div>
          <div class="profile-item">
            <h2>Fitness Level:</h2> <h3><%= @user.fitness_level %></h3>
          </div>
        </div>
        <div class="profileCard">
          <div class="profile-item">
            <h2>Preferred Workout Location:</h2> <h3><%= @user.location %></h3>
          </div>
          <div class="profile-item">
            <h2>Availability:</h2>
            <div class="scheduleProfile">
              <div class="dayOfWeekLabels">
              </div>
              <div class="scheduleFlex">
                <div class="schedule-day timeOfDayLabels">
                  <h4 class="label-style-schedule">Morning</h4>
                  <h4 class="label-style-schedule">Afternoon</h4>
                  <h4 class="label-style-schedule">Evening</h4>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">MON</h4>
                  <div class="<%= availabilityMatch?(@user, 'mon_morn') %>" id="monMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'mon_aft') %>" id="monAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'mon_eve') %>" id="monEve"></div>
                </div>
                <div class="schedule-day">
                  <div class="schedule-day">
                    <h4 class="label-style-schedule scheduleShowLabel">TUE</h4>
                    <div class="<%= availabilityMatch?(@user, 'tues_morn') %>" id="tuesMorn"></div>
                    <div class="<%= availabilityMatch?(@user, 'tues_aft') %>" id="tuesAft"></div>
                    <div class="<%= availabilityMatch?(@user, 'tues_eve') %>" id="tuesEve"></div>
                  </div>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">WED</h4>
                  <div class="<%= availabilityMatch?(@user, 'wed_morn') %>" id="wedMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'wed_aft') %>" id="wedAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'wed_eve') %>" id="wedEve"></div>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">THU</h4>
                  <div class="<%= availabilityMatch?(@user, 'thurs_morn') %>" id="thursMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'thurs_aft') %>" id="thursAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'thurs_eve') %>" id="thursEve"></div>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">FRI</h4>
                  <div class="<%= availabilityMatch?(@user, 'fri_morn') %>" id="friMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'fri_aft') %>" id="friAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'fri_eve') %>" id="friEve"></div>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">SAT</h4>
                  <div class="<%= availabilityMatch?(@user, 'sat_morn') %>" id="satMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'sat_aft') %>" id="satAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'sat_eve') %>" id="satEve"></div>
                </div>
                <div class="schedule-day">
                  <h4 class="label-style-schedule scheduleShowLabel">SUN</h4>
                  <div class="<%= availabilityMatch?(@user, 'sun_morn') %>" id="sunMorn"></div>
                  <div class="<%= availabilityMatch?(@user, 'sun_aft') %>" id="sunAft"></div>
                  <div class="<%= availabilityMatch?(@user, 'sun_eve') %>" id="sunEve"></div>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="profileCard lastProfileCard">
          <div class="profile-item">
            <p><%= @user.description %></p>
          </div>
        </div>
      </div>
    </div>

    <% if @user == current_user %>
    <div class="iconFlexContainer">
      <div class="icon-button">
        <%= link_to edit_user_path(current_user.id) do %>
        <%= image_tag("settings.svg") %>
      </div>
      <h2>Edit Profile</h2>
      <% end %>
    </div>
    <% end %>
</section>