config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'users/registrations' }
    authenticated :user do

      root 'users#home', as: :authenticated_root
      get '/home', to: 'users#home'
    end

    root 'landings#index'

    resources :users, only: [:index, :show, :edit, :update]
    resources :landings, only: [:index]

    resources :personal_messages, only: [:new, :create]
    resources :conversations, only: [:index, :show]


    get '/discover', to: 'events#discover'
    get '/gymbuddy', to: 'users#gym_buddy'

    resources :events do
      resources :tickets, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

end

app/views/shared/_landing_nav_bar.html.erb
<nav class="navBar">
  <%= link_to root_url do %>
    <div class="gymmelogo-container">
      <h1 class="gymme-logo">Gymme</h1>
    </div>
  <% end %>
  <div class="landing-nav-item-container">

    <ul class="navBar-items">
      <div class="nav-button">
        <a href="/#meetYourMatch"><li class="desktop nav-item"> Meet Your Match </li></a>
      </div>
      <div class="nav-button">
        <a href="/#findEvent"><li class="desktop nav-item"> Find an Event </li></a>
      </div>
      <div class="nav-button">
        <a href="/#testimonials"><li class="desktop nav-item"> Testimonials </li></a>
      </div>
    </ul>
    <ul class="navBar-items drop-down-items" id="landingNavDropDownItems">
      <div class="nav-button">
        <a href="/#meetYourMatch"><li class="desktop nav-item"> Meet Your Match </li></a>
      </div>
      <div class="nav-button">
        <a href="/#findEvent"><li class="desktop nav-item"> Find an Event </li></a>
      </div>
      <div class="nav-button">
        <a href="/#testimonials"><li class="desktop nav-item"> Testimonials </li></a>
      </div>
    </ul>

    <div class="hamburger-menu-icon" id="hamburgerMenuIcon">
      <%= image_tag("menu.svg") %>
    </div>

  </div>

</nav>

<div class="screen-cover drop-down-screen-cover-tint" id="dropDownScreenCover"></div>

app/views/shared/_nav_bar.html.erb
<% if current_user %>
<nav class="navBar">
  <%= link_to home_path(current_user.id) do %>
    <div class="gymmelogo-container">
      <h1 class="gymme-logo">Gymme</h1>
    </div>
  <% end %>

  <div class="nav-item-container">
    <ul class="navBar-items" id="navBarItems">
      <div class="nav-button">
        <%= link_to home_path(current_user.id) do %>
          <li class="desktop nav-item"> Home </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to discover_path do %>
          <li class="desktop nav-item"> Discover Events </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to gymbuddy_path do %>
          <li class="desktop nav-item"> Find Gym Buddy </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to conversations_path do %>
          <li class="desktop nav-item"> Messages </li>
        <% end %>
      </div>
    </ul>
    <ul class="navBar-items drop-down-items" id="dropDownItems">
      <div class="nav-button">
        <%= link_to home_path(current_user.id) do %>
          <li class="desktop nav-item"> Home </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to discover_path do %>
          <li class="desktop nav-item"> Discover Events </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to gymbuddy_path do %>
          <li class="desktop nav-item"> Find Gym Buddy </li>
        <% end %>
      </div>
      <div class="nav-button">
        <%= link_to conversations_path do %>
          <li class="desktop nav-item"> Messages </li>
        <% end %>
      </div>
    </ul>


    <div class="profile-button" id="profile-avatar-button">
      <% if current_user.avatar.attached? %>
        <div class="avatar">
          <%= image_tag url_for(current_user.avatar) %>
        </div>
      <% else %>
        <div class="avatar">
          <%= image_tag(user_avatar(current_user)) %>
        </div>
      <% end %>
      <span>&#x25BC;</span>
    </div>
  </div>

  <section class="user-options-modal hidden" id="userMenu">
    <ul class="user-options">
      <div class="nav-button mainNavOption">
        <%= link_to home_path(current_user.id) do %>
          <li class="desktop nav-item"> Home </li>
        <% end %>
      </div>
      <div class="nav-button mainNavOption">
        <%= link_to discover_path do %>
          <li class="desktop nav-item"> Discover Events </li>
        <% end %>
      </div>
      <div class="nav-button mainNavOption">
        <%= link_to gymbuddy_path do %>
          <li class="desktop nav-item"> Find Gym Buddy </li>
        <% end %>
      </div>
      <div class="nav-button mainNavOption">
        <%= link_to conversations_path do %>
          <li class="desktop nav-item"> Messages </li>
        <% end %>
      </div>
      <div class="nav-button-extra">
        <%= link_to new_event_path do %>
        <li class="nav-item">Create Event</li>
        <% end %>
      </div>
      <div class="nav-button-extra">
        <%= link_to user_path(current_user.id) do %>
        <li class="nav-item">Profile</li>
        <% end %>
      </div>
      <div class="nav-button-extra">
        <%= link_to destroy_user_session_path, method: :delete do %>
        <li class="nav-item logout">Logout</li>
        <% end %>
      </div>
    </ul>
  </section>
<% end %>
</nav>
<div class="screen-cover drop-down-screen-cover-tint" id="dropDownScreenCover"></div>