config/routes.rb
Rails.application.routes.draw do

    mount ActionCable.server => '/cable'

    devise_for :users, controllers: { registrations: 'users/registrations' }
    authenticated :user do

      root 'users#home', as: :authenticated_root
      get '/home', to: 'users#home'
    end

    root 'landings#index'

    resources :users, only: [:index, :show, :edit, :update]
    resources :landings, only: [:index]

    resources :personal_messages, only: [:new, :create]
    resources :conversations, only: [:index, :show]


    get '/discover', to: 'events#discover'
    get '/gymbuddy', to: 'users#gym_buddy'

    resources :events do
      resources :tickets, only: [:create, :destroy]
      resources :comments, only: [:create, :destroy]
    end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :owner, foreign_key: 'user_id', class_name: 'User'
  has_many :tickets
  has_many :users, through: :tickets
  has_many :comments
  validate :date_not_in_past


  geocoded_by :address
  after_validation :geocode, if: :address_changed?

  validates :title, :address, :time, :description, :activity_type, presence: true



  def date_not_in_past
    if self.time && self.time < DateTime.current
      errors.add(:time, "Date can't be in the past")
    end
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  def discover

  end

  def index
    @events = Event.all
    if params[:search].present?
      radius = params[:radius]
      search_location_lat = Geocoder.search(params[:search])[0].data["lat"]
      search_location_lon = Geocoder.search(params[:search])[0].data["lon"]
      @events = Event.near([search_location_lat, search_location_lon], radius, units: :km)
    end
    @events = @events.where(activity_type: params[:activity_type]) if params[:activity_type].present?
    @events = @events.where("capacity > ?", 0)
    @events = @events.where("time > ?", DateTime.now)
    @events = @events.order(:time)

  end

  def show
    @event = Event.find(params[:id])
    @comments = @event.comments
    @comment = Comment.new
    @users = @event.users

    if current_user
      @ticket = Ticket.find_by(user_id: current_user.id, event_id: @event.id)
    end
  end

  def new
    @event = Event.new
  end

  def create
    @event = Event.new
    @event.title = params[:event][:title]
    @event.address = params[:event][:address]
    @event.time = params[:event][:time]
    @event.end_date = params[:event][:end_date]
    @event.persistence = params[:event][:persistence]
    @event.description = params[:event][:description]
    @event.activity_type = params[:event][:activity_type]
    @event.capacity = params[:event][:capacity]
    @event.need_approval = params[:event][:need_approval]
    @event.user_id = current_user.id
      if params[:event][:activity_type] == "Yoga/Pilates"
        @event.activity_icon = "lotus-position.svg"
      elsif params[:event][:activity_type] == "Resistence Training"
        @event.activity_icon = "dumbbell.svg"
      elsif params[:event][:activity_type] == "Cardio"
        @event.activity_icon = "athletics.svg"
      else params[:event][:activity_type] == "Recreation"
        @event.activity_icon = "american-football.svg"
      end

    if @event.save
      redirect_to event_path(@event)
    else
      flash[:alert] = "Something went wrong"
      render :new
    end
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = Event.find(params[:id])

    @event.title = params[:event][:title]
    @event.address = params[:event][:address]
    @event.time = params[:event][:time]
    @event.description = params[:event][:description]
    @event.activity_type = params[:event][:activity_type]
    @event.capacity = params[:event][:capacity]
    @event.need_approval = params[:event][:need_approval]
    @event.user_id = current_user.id

    if @event.save
      redirect_to event_path(@event)
    else
      flash[:alert] = "Something went wrong"
      render :edit
    end

  end


end

app/helpers/events_helper.rb
module EventsHelper
    
end

app/views/events/_event_form.html.erb
<%= form_for event do |f| %>

  <div class="form-card">
    <div class="form-item-icon">
      <%= image_tag "worldwide.svg" %>
    </div>
    <div class="form-item">
      <h3><%= f.label "Where will your event be located?" %></h3>
      <p><%= f.text_field :address, placeholder: "ex. Toronto, ON", id: "locationSearchField" %></p>
    </div>
  </div>

  <div class="form-card">

    <div class="form-item-icon">
      <%= image_tag "calendar.svg" %>
    </div>
    <div class="form-item">
      <h3><%= f.label "What date and time?" %></h3>
      <p><%= f.datetime_field :time %></p>
    </div>
  </div>

  <div class="form-card">
    <div class="form-item-icon">
      <%= image_tag "gym.svg" %>
    </div>
    <div class="form-item">
      <h3><%= f.label "What type of activity will you be doing?" %></h3>
      <p><%= f.select :activity_type, ["Yoga/Pilates", "Resistence Training", "Cardio", "Recreation"]%></p>
    </div>
  </div>

  <div class="form-card">
    <div class="form-item-icon">
      <%= image_tag "group-of-students.svg" %>
    </div>
    <div class="form-item">
      <h3><%= f.label "How many people do you want to join?" %></h3>
      <p><%= f.number_field :capacity, placeholder: "leave blank for no limit" %></p>
    </div>
  </div>

  <div class="form-card description">
    <div class="form-item-icon">
      <%= image_tag "tag.svg" %>
    </div>
    <div class="form-item">
      <h3><%= f.label "What do you want the event to be called?" %></h3>
      <p><%= f.text_field :title, placeholder: "ex. Jog By The Lake"%></p>
    </div>
    <div class="form-item description">
      <h3><%= f.label "What is a quick description?" %></h3>
      <p><%= f.text_area :description, placeholder: 'ex. "Looking for a group for a 10k run by the lake"' %></p>
    </div>
  </div>

  <div class="form-item submit">
    <h3><%= f.submit "Create Event" %></h3>
  </div>

<% end %>

app/views/events/_event_ticket.html.erb
<!-- Check if user is signed in, and if they have joined the event  -->

<% if @event.capacity %>
<div class="ticketAttendance">
  <div class="ticketSpots">Spots Left</div>
  <p><%= @event.capacity %></p>
</div>
<% else %>
<div class="ticketAttendance">
  <p><%= @event.users.length %> attending</p>
</div>
<% end %>
<% if current_user == @event.owner %>
  <%= link_to "Edit Event", edit_event_path(@event.id) %>
<% elsif joined_event? %>
  <p class="ticketJoinedMessage">You're on the list!</p>
  <%= link_to "Can't Go", event_ticket_path(@event.id, @ticket.id), method: :delete %>
<% elsif current_user && current_user != @event.owner && @event.capacity > 0 %>
  <%= button_to "Join Event", event_tickets_path(@event) %>
<% elsif @event.capacity == 0 %>
  <div class="ticketAttendance">
    <h4>Event is currently full.</h4>
  </div>
<% elsif !current_user %>
  <div class="ticketAttendance">
    <h4><%= link_to "Log-in", new_user_session_path %> to join event</h4>
  </div>
<% end %>

app/views/events/discover.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>

<section class="create-new-event">
  <div class="discover-hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Find an Event</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll connect you with a new squad.</h2>
    </div>
  </div>

  <nav class="search">
    <%= form_tag events_path, method: :get do %>
      <div class="form-card discover">
        <div class="form-item-icon">
          <%= image_tag "worldwide.svg" %>
        </div>
        <div class="form-item">
          <h2 class="activity-type-header">Find Events Near</h2>
          <%= text_field_tag :search, current_user.location, id: "locationSearchField" %>
        </div>
        <div class="form-item">
          <h2 class="activity-type-header">Radius</h2>
          <%= select_tag :radius, options_for_select([["1km", 1], ["2km", 2], ["5km", 5], ["10km", 10], ["15km", 15], ["20km", 20], ["30km", 30], ["40km", 40], ["50km", 50], ["60km", 60], ["70km", 70], ["80km", 80], ["90km", 90], ["100km", 100]], selected: 20), include_blank: false %>
        </div>
      </div>
      <div class="form-card discover">
        <h2 class="activity-type-header">What type of activity are you looking for?</h2>
        <div class="activity-icons-wrapper">
          <div class="activity-icon">
            <p class="activity-type-description">Yoga/Pilates</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Yoga/Pilates", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("lotus-position.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Resistence</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Resistence Training", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("exercise.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Cardio</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Cardio", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("athletics.svg") %>
            </label>
          </div>
          <div class="activity-icon">
            <p class="activity-type-description">Recreation</p>
            <label class="activity-type hide-radio-button">
              <%= radio_button_tag :activity_type, "Recreation", checked = false %>
              <div class="clickedRadioCircle"></div>
              <%= image_tag("american-football.svg") %>
            </label>
          </div>
          <label class="activity-type hide-radio-button">
            <%= radio_button_tag :activity_type, "", checked = true %>
            <div class="clickedRadioSquare"></div>
            <div class="activity-icon-all">All Types</div>
          </label>
        </div>
      </div>
      <div class="form-submit">
        <div class="large-submit-button">
          <%= submit_tag "Find Events" %>
        </div>
      </div>
      <% end %>
    </nav>


</section>

app/views/events/edit.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>


<section class="create-new-event">

  <div class="hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Edit Your Event</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll help find you some awesome people.</h2>
    </div>
  </div>

  <div class="text-danger">
  <% prevError = "" %>
  <% @event.errors.messages.each do |attribute, errors| %>
    <% if prevError != errors[0] %>
      <p>* <%= errors[0].capitalize %></p>
    <% end %>
    <% prevError = errors[0] %>
  <% end %>
  </div>


  <section class="new-event-form">
    <%= render "event_form", event: @event %>
  </section>
</section>

app/views/events/index.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>

<section class="create-new-event">

  <div class="discover-hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Find an Event</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll connect you with a new squad.</h2>
    </div>
  </div>
</section>

<header class="event-index">
  <h1 class="index-header">Refine Your Search</h1>
  <nav class="search">
    <%= form_tag events_path, method: :get do %>
        <%= select_tag :activity_type, options_for_select([["All Fitness Types", nil], "Yoga/Pilates", "Resistence Training", "Cardio", "Recreation"], selected: params[:activity_type]), include_blank: false %>
        <%= text_field_tag :search, params[:search], id: "locationSearchField" %>
        <%= select_tag :radius, options_for_select([["1km", 1], ["2km", 2], ["5km", 5], ["10km", 10], ["15km", 15], ["20km", 20], ["30km", 30], ["40km", 40], ["50km", 50], ["60km", 60], ["70km", 70], ["80km", 80], ["90km", 90], ["100km", 100]], selected: params[:radius]), include_blank: false %>

        <%= submit_tag "Filter" %>
    <% end %>

  </nav>

</header>

<section class="event-reults home">
  <% if @events.length == 0 %>
    <h3 class="event-title noMatch">Sorry, No Events Found</h3>
    <div class="event-icon noMatch"><%= image_tag("friends.svg") %></div>
    <p class="address">Please try again with a new activity or radius</p>
  <% else %>
    <p class="map-icon-description" id="hide-map-desc">Hide Map</p>
    <p class="hidden map-icon-description" id="show-map-desc">Show Map</p>
    <div class="map-icon" id="map-button">
      <%= image_tag("noun_Map.png") %>
    </div>
    <div class="map-container">
      <!-- Render Events Map -->
      <div class"event-index-map" id="eventsMap" ></div>
      <% @events.each do | event | %>
        <div class="eventsLatLong" data-latitude="<%= event.latitude %>" data-longitude="<%= event.longitude %>"></div>
        <div class="eventsMarkerTitle" data-title="<%= event.title %>"></div>
      <% end %>
    </div>

    <% @events.each do |event| %>
      <%= link_to event_url(event.id) do %>
        <div class="event-card">
          <div class="event-icon-container">
            <div class="event-icon"><%= image_tag(event_activity_icon(event)) %></div>
          </div>
          <div class="event-info">
            <p class="date"><%= event.time.strftime("%A %b %d, %Y") %> • <%= event.time.strftime("%I:%M%p") %></p>
            <h3 class="event-title"><%= event.title %></h3>
            <p class="address"><%= event.address %></p>
          </div>
        </div>
      <% end %>
    <% end %>

  <% end %>

</section>

app/views/events/new.html.erb
<div class="navBarContainer">
<% if current_user %>
  <%= render "shared/nav_bar" %>
<% else %>
  <%= render "shared/landing_nav_bar" %>
<% end %>
</div>


<section class="create-new-event">

  <div class="hero-image">
    <div class="new-event top-heading">
      <h1 class="new-event-heading">Create an Event</h1>
    </div>
    <div class="new-event sub-heading">
      <h2 class="new-event-heading">We’ll help find you some awesome people.</h2>
    </div>
  </div>

  <div class="text-danger">
  <% prevError = "" %>
  <% @event.errors.messages.each do |attribute, errors| %>
    <% if prevError != errors[0] %>
      <p>* <%= errors[0].capitalize %></p>
    <% end %>
    <% prevError = errors[0] %>
  <% end %>
  </div>

  <section class="new-event-form">
    <%= render "event_form", event: @event %>
  </section>

</section>

app/views/events/show.html.erb
<div class="eventShowBackground">
  <div class="navBarContainer">
    <% if current_user %>
    <%= render "shared/nav_bar" %>
    <% else %>
    <%= render "shared/landing_nav_bar" %>
    <% end %>
  </div>


  <header class="eventShowHeader">
    <div class="eventHeaderFlexContainer">
      <div class="event-show-info">
        <p class="event-date"><%= @event.time.strftime("%A %b %d, %Y") %> • <%= @event.time.strftime("%I:%M%p") %></p>
        <h1 id="eventName" class="event-name"><%= @event.title %></h1>
        <div class="eventHostFlexContainer">
          <% if @event.owner.first_name && @event.owner.last_name %>
            <p class="eventInfoBoxText">Hosted by</p>
            <%= link_to user_path(@event.owner.id) do %>
            <div class="avatar">
              <%= image_tag url_for(user_avatar(@event.owner)) %>
            </div>
            <p class="event-owner"><%= full_name(@event.owner) %></p>
            <% end %>
          <% elsif @event.owner.first_name %>
            <p class="eventInfoBoxText">Hosted by</p>
            <%= link_to user_path(@event.owner.id) do %>
            <div class="avatar">
              <%= image_tag url_for(user_avatar(@event.owner)) %>
            </div>
            <p class="event-owner"><%= full_name(@event.owner.first_name) %></p>
            <% end %>
          <% else %>
            <p class="eventInfoBoxText">Hosted by</p>
            <%= link_to user_path(@event.owner.id) do %>
            <div class="avatar">
              <%= image_tag url_for(user_avatar(@event.owner)) %>
            </div>
            <p class="event-owner"><%= @event.owner.email %></p>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </header>

  <section class="eventTicketBar">
    <div class="eventTicketBounds">
      <div class="eventTicketContainer">
        <div class="eventTicketInfo">
          <p class="event-date"><%= @event.time.strftime("%A %b %d") %> • <%= @event.time.strftime("%I:%M%p") %></p>
          <h1 id="eventName" class="eventTicketName"><%= @event.title %></h1>
        </div>
        <div class="eventTicket">
          <%= render "event_ticket" %>
        </div>
      </div>
    </div>
  </section>

  <div class="eventPageContainer">
    <section class="event-page">
      <div class="event-body-container">
        <div class="eventInfoFlexContainer">
          <div class="eventInfoBox">
            <p class="eventInfoBoxText"><%= @event.time.strftime("%A %b %d, %Y") %> • <%= @event.time.strftime("%I:%M%p") %></p>
            <p class="eventInfoBoxText"><%= @event.address %></p>
            <div class="map-icon" id="map-button">
              <p id="showText">hide</p>
              <p class="hidden" id="hideText">show</p>
              <%= image_tag("noun_Map.png") %>
            </div>
          </div>
          <iframe
            id="eventsMap"
            width="400"
            height="400"
            frameborder="0" style="border:0" label="none"
            src="https://www.google.com/maps/embed/v1/place?key=<%= ENV["GYMME_MAPS_KEY"] %>
              &q=<%= @event.address %>" allowfullscreen >
          </iframe>
        </div>
        <div class="eventDetailsCommentsContainer">
          <div class="event-details-continer">
            <h3 class="event-header">Details</h3>
            <p class="event-details"><%= @event.description %></p>
          </div>
          <div class="usersAttendingContainer">
            <h3 class="event-header">Attending (<%= @event.users.length %>) <span class="seeAllUsers" id="seeAllUsersButton">See all</span></h3>
            <div class="usersAttendingFlexContainer">
              <% @event.tickets.each_with_index do |ticket, index| %>
              <% user = User.find(ticket.user_id) %>
                <% if index < 4 %>
                  <div class="userAttendingCard">
                    <%= link_to user_path(user) do %>
                    <div class="userAttendingAvatar">
                      <%= image_tag url_for(user_avatar(user)) %>
                    </div>
                    <p class="userAttendingName"><%= full_name(user) %></p>
                    <% end %>
                  </div>
                <% else %>
                  <div class="userAttendingCard longGuestListHidden longGuestListItem">
                    <%= link_to user_path(user) do %>
                    <div class="userAttendingAvatar">
                      <%= image_tag url_for(user_avatar(user)) %>
                    </div>
                    <p class="userAttendingName"><%= full_name(user) %></p>
                    <% end %>
                  </div>
                <% end %>
              <% end %>
            </div>
          </div>
          <div class="commentAreaContainer">
            <section class="comment-area">
              <%= form_for( @comment, url: event_comments_path(@event.id) ) do |f| %>
              <div class="field">
                <%= f.label "Leave a comment" %><br/>
                <%= f.text_area :body %>
              </div>
              <div class="actions">
                <%= f.submit "Comment" %>
              </div>
              <% end %>
              <% if current_user  %>
                <% @comments.reverse_each do |comment| %>
                <div class="comment">
                  <p class="comment-time"><em><%= comment.created_at.strftime("%m/%d/%Y at %I:%M%p") %></em></p>
                  <% if comment.user.full_name %>
                    <p class="comment-user"><%= comment.user.full_name %></p>
                  <% else %>
                    <p class="comment-user"><%= comment.user.email %></p>
                  <% end %>
                  <p class="comment-body"><%= comment.body %></p>
                  <!-- Check if user created comment to have authorization to delete it  -->
                  <% if comment.user.id == current_user.id %>
                    <%= button_to "delete", event_comment_path(@event, comment.id), data: { confirm: "Are you sure?" }, method: :delete %>
                  <% end %>
                </div>
                <% end %>
              <% end %>
            </section>
          </div>
        </div>
      </div>
    </section>
  </div>


</div>